vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /uploads/images/posters
            upload_destination: '%upload_directory_posters%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        portrait_file:
            uri_prefix: /uploads/images/portrait
            upload_destination: '%upload_directory_portrait%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
